# Generated by Django 5.0.1 on 2024-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_intro_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publicado_em']},
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
