# Generated by Django 5.0.1 on 2024-01-24 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
